apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafka-test-apps-us
  labels:
    strimzi.io/cluster: my-cluster-us
spec:
  partitions: 12
  replicas: 3
  config:
      retention.bytes: 1073741824
      retention.ms: 86400000
      segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafka-test-apps-europe
  labels:
    strimzi.io/cluster: my-cluster-us
spec:
  partitions: 12
  replicas: 3
  config:
      retention.bytes: 1073741824
      retention.ms: 86400000
      segment.bytes: 1073741824
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: scholzj/kafka-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-us-kafka-bootstrap:9092
          - name: TOPIC
            value: kafka-test-apps-us
          - name: TIMER
            value: "1000"
          - name: NUMBER_OF_KEYS
            value: "20"
          - name: MESSAGE
            value: "From us-east-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: scholzj/kafka-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-us-kafka-bootstrap:9092
          - name: PATTERN
            value: "kafka-test-apps.*"
          - name: GROUP_ID
            value: my-us-east-1-consumer
